### PR TITLE
Initial Implementation

### PR DESCRIPTION
**Pull request by MeirionHughes**
Managed to rebase as a single commit; should be good to go.

### CODE REVIEW

**Comment by MeirionHughes** [comment]
Will update this to RC

**Comment by MeirionHughes** [comment]
Working on RC, Tests passing.

**Comment by EisenbergEffect** [comment]
@MeirionHughes How do you feel about the status? Do you feel it's ready to merge? We'll need to fix it up to have a build process in-line with our other repos, but that aside, what do you think?

**Comment by MeirionHughes** [comment]
There are a few duplicated interfaces that, ideally, should be imported from `aurelia-templating` and `aurelia-templating-binding`, But, given it needs cleaning to your own standards anyway... it might be better to run with it and change as you see fit. Up to you; its already published to npm (`aureliaeffect` has ownership) and it works fine for the linter. That said, I'm not using ViewCompiler; just the expression/binding generators + DI container.

**Comment by EisenbergEffect** [comment]
@martingust This represents the first steps toward server-side rendering. Can you do a review of the implementation?

@niieani Once we merge this, would you be able to help in fixing up the build process to match our other repositories? Since this code is fully written in TypeScript, we can use it as an opportunity to explore what our ideal TS-based build might look like.

**Comment by niieani** [comment]
@EisenbergEffect Sure! In fact, the last remaining use-case we had for Babel, i.e. transpilation to `native-modules` while still targetting **es5**, is supported as of TypeScript 2.0, so modifying our build implementation to fit should now be a breeze.

**Comment by EisenbergEffect** [comment]
@MeirionHughes Can you rebase this PR on the master branch? Thanks!

**Comment by MeirionHughes** [comment]
Sorry for the delay; been a bit swamped with work and life. :P

**Comment by MeirionHughes** [comment]
Its crazy how much can change in a few weeks... some of the stuff I'm doing in this commit I probably wouldn't do the same now. e.g. compiling the spec ts->js and then deleting the js afterward isn't needed, you can simply tell your IDE (VSCode) to ignore any js/map file when there is a corresponding ts file.

**Comment by niieani** [comment]
Hey @MeirionHughes, how is it going with the PR? I'd love to give this a try.
Big thanks for working on this.

**Comment by MeirionHughes** [comment]
Its been in limbo for a while. I think its waiting on someone from aurelia to take it and add it to your build. 

I've published to npm already and https://www.npmjs.com/package/aurelia-template-lint is using it happily, so you could run with that if need be. 

I suspect there is a targeting issue though because I've had people complain they cannot use node 4 with the linter.

**Comment by niieani** [comment]
@MeirionHughes can you explain what would be the next step with this now? What do you mean by "add it to your build"? I might be able to try it out when I have a bit more time.
@EisenbergEffect is there anyone in charge of Aurelia server-side generation?

**Comment by EisenbergEffect** [comment]
Martin is, sort of. But no one has really taken the lead just yet. If you want to handle this, that would be great. I think the PR just needs to be modified to have a property build setup and repo structure.

**Comment by niieani** [comment]
To make server-side generation optimal I think it would be a good idea to also make an aurelia-loader-nodejs (or better: enhance the default loader) to support NodeJS sync-style `require()` dependency loading. It'll be useful for Electron too. I can look into that, possibly also server-side generation, but I've got a lot on my plate already anyway.

**Comment by EisenbergEffect** [comment]
Feel free to look into that but don't feel obligated. Martin will be jumping in on this soon as well.

**Comment by martingust** [comment]
@EisenbergEffect @niieani @MeirionHughes I have read through the code and it looks pretty good to me and we can iterate over it along the way server side generation gets implemented. If we merge this I can modify the repo structure. @EisenbergEffect what do you mean by "a property build"? @niieani Assuming you still have a lot on your plate (?) I can start looking at the loader and server side generation and collaborate the implementation with you?

**Comment by EisenbergEffect** [comment]
I think that was a typo and I meant "proper build". I'll go ahead and merge this so we can move forward with getting things in place and working on server render.

**Comment by niieani** [comment]
@martingust that sounds good. I'm still quite busy, but if you start something ping me and I'll see how much time I can invest into it.
I have some great ideas for server-rendering use-cases, e.g. building and generating static sites using Aurelia's components, something that [Gatsby](https://github.com/gatsbyjs/gatsby) is trying to do for React. If done right, I think this could really popularize Aurelia.

**Pull request merged**
