### PR TITLE
refactor(MO): convert polyfill to class impl.

### PR DESCRIPTION
**Pull request by devanp92**
The purpose of this commit is to split the MO polyfill into separate classes introduced in #5.

@MeirionHughes Do you think this can be refactored any further?

@martingust - Similarly to the last [PR](https://github.com/aurelia/pal-nodejs/pull/5), this should be split into separate files - although, gulp doesn't recognize ANY tests when I added a new file to src/. I tried to figure out this issue - but couldn't find a solution.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@MeirionHughes Can you review?

**Comment by MeirionHughes** [comment]
@devanp92 I need to make some changes to the repo to get it back to where I left it; plus we need a test runner before any more merges.

**Comment by devanp92** [comment]
Closing PR

**Comment by MeirionHughes** [comment]
Yeah, I'm inclined to finalize the original I started. The poly-fill was a nice idea, but not being able able to detect the text-node changes simply replaces one problem with another. Plus, when I converted the repo back to typescript it kind of blew up with errors. :D

**Pull request closed without merging**
