### PR TITLE
feat(index): move isInitialized to aurelia-pal + globalize function

### PR DESCRIPTION
**Pull request by niieani**
Two things:

1. move `isInitialized` to aurelia/pal#16
2. globalize function which initializes and globalizes variables like 'window'

### CODE REVIEW

**Comment by niieani** [comment]
@stsje changed the code to use `hasOwnProperty`

**Comment by stsje** [comment]
@niieani I don't see any documentation for `TextImpl`, which I suspect is a special case for jsdom that has been mentioned?
If `TextImpl` doesn't exist, then I'm afraid the next call to `implementation.hasOwnProperty` will throw an exception.

**Comment by niieani** [comment]
TextImpl does exist if you take a look at the source of JSDOM. Not sure if polyfilling that one is needed, since `Text` is the generated file that actually contains `TextImpl` within. But I don't see any reason why not do it, even if just to be safe.
Polyfill is only used with JSDOM, pal-nodejs needs JSDOM, so in a way, polyfill is used by pal-nodejs. ;) @jdanyow sent a PR to JSDOM, but they're being pretty slow about merging it, so it might land in a few months, and we need server-rendering by yesterday.

**Comment by MeirionHughes** [comment]
To be fair I make some rather crude polyfills too for the notify change stuff; they've been sitting on MutationObserver pr for 2 years.

**Comment by niieani** [comment]
@EisenbergEffect note that the test fails cause [recent updates](https://github.com/aurelia/pal/pull/16) to aurelia-pal weren't released yet.

**Pull request merged**
