### PR TITLE
feat: update jsdom v15.0.0 to improve compatibility of browser simulation

### PR DESCRIPTION
**Pull request by 3cp**
Removed internal MutationObserver polyfill in favour of jsdom's offering.
    Simpified and enhanced global vars creations for simulating browser environment, thank browser-env. It improves compatibility with other 3rd party libs in user's app, for example, global vars navigator/sessionStorage/localStorage are now available.
    This also provides an alternative way to improve the compatibility of test setup in jest, comparing to aurelia/cli#1019.

### CODE REVIEW

**Comment by huochunpeng** [comment]
There is a TS type checking error on existing code, I don't know how to fix it.

```
src/nodejs-platform.ts(47,5): error TS2322: Type 'Immediate' is not assignable to type 'number'.
```

nodejs-platform.js
```js
  requestAnimationFrame(callback: (animationFrameStart: number) => void): number {
    return setImmediate(callback); // this one is type 'Immediate'
  }
```

**Comment by JeroenVinke** [comment]
We should test the ssr setup for memory leaks

**Comment by Vheissu** [comment]
I tested this and it fixed the issue I had previously. As for SSR, I've fallen down that rabbit hole quite a bit and honestly, our current SSR solution is really hard to debug.

**Comment by huochunpeng** [comment]
@Vheissu can you have a quick test on the updated jsdom v15?
@jeremy-holt also had positive result with this improvement, and has been waiting for the release.

We probably need to review and release this sooner than later. It has been a while.

@fkleuver the circleci config seems to be wrong.

**Comment by fkleuver** [comment]
@huochunpeng I never touched this circleci config, the config file version just got deprecated. Can we have `npm run build`, `npm run test` and `npm run cut-release` npm scripts here like the rest of the repos do? Then circleci config can be copy pasted from one of the other migrated repos.

**Comment by 3cp** [comment]
I have fixed the outdated circleci v1 config. Can we get this one going?

**Comment by 3cp** [comment]
Oh, I missed the existing circleci config from other repo. Will copy one over.

**Comment by 3cp** [comment]
I will leave npm scripts change to a separated PR.

**Comment by 3cp** [comment]
@Vheissu @EisenbergEffect could someone help testing ssr?

This PR is stale for too long. Our jsdom is so outdated, it feels like pre-history.

**Comment by ghiscoding** [comment]
If that can help in upgrading the JSDOM, here's what Jest wrote on their latest version 25 [blog post](https://jestjs.io/blog/2020/01/21/jest-25)

> Jest 25 is laying the groundwork for many major changes in the future. As such, we kept breaking changes to a minimum, but internal architecture changes may require attention during the upgrade. The main changes are an upgrade of JSDOM from v11 to v15, 10-15% faster test runs, a new diff view for outdated snapshots and dropped Node 6 support.

> **Bye Node 6**
> Node 6 has been EOL since April 30th 2019, and Jest 25 leaves it behind. Dropping Node 6 means we can upgrade our dependencies, the main one being JSDOM, which has been upgraded to version 15.

**Comment by EisenbergEffect** [comment]
@3cp What's really needed on this? Do I just need to check it out and run the tests?

**Comment by 3cp** [comment]
Not sure, @JeroenVinke and @Vheissu mentioned checking SSR memory leak. I never touched SSR.

**Comment by EisenbergEffect** [comment]
I've never had a need for SSR myself, so I would have to defer to @JeroenVinke or @Vheissu 
I'm happy to merge and release if this is good. It seems pretty straight forward...

**Comment by JeroenVinke** [comment]
I can have a look tonight. When I worked on the initial implementation there were a lot of memory leaks. I usually fire a lot of requests to the server and compare the memory usage after the initial request and after all the other requests

**Comment by EisenbergEffect** [comment]
Thanks @JeroenVinke We appreciate it!

**Comment by JeroenVinke** [comment]
Ok this seems to work fine. I would recommend to also bump https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-typescript-webpack-ssr/package.json#L101 to ^2.5.2 and https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-typescript-webpack-ssr/package.json#L81 to ^15.1.1. Otherwise you get multiple versions of aurelia-binding, and then we can't effectively disable the dirty checker which causes memory problems because of the setTimeout it uses internally.

I did get some typescript errors while creating the bundle (loads of `[at-loader] ./node_modules/aurelia-dependency-injection/dist/aurelia-dependency-injection.d.ts:134:162
[server]     TS2536: Type 'number' cannot be used to index type 'TArgs'.`), but maybe that's just because my environment is not up to date

**Comment by 3cp** [comment]
That https://github.com/aurelia/skeleton-navigation is way out dated.
We got a resolve alias webpack config in cli skeleton in place to fix all possible aurelia-binding version issue.

Maybe put that repo to archived, and a deprecation message: "use aurelia-cli instead"? @EisenbergEffect

**Comment by 3cp** [comment]
I double checked in 2 latest cli generated apps, webpack+ts+jest, cli-bundler+ts+jest, all worked fine without any tsc errors.

@EisenbergEffect let's release this one.

Note:
1. gulp v3 doesn't work in nodejs v12, please use nodejs v10 for release.
2. I confirm all dist files are update to date, matching src.
3. this is technically a breaking change for a major release, as jsdom dropped nodejs v6 support.

Latest jsdom is v16, but it dropped nodejs v8 support. I think keep it at v15 to support nodejs v8, as jest did the same.

We can update cli to this new version, before next cli release.

**Comment by ghiscoding** [comment]
@3cp
> Latest jsdom is v16, but it dropped nodejs v8 support. I think keep it at v15 to support nodejs v8, as jest did the same.

Technically speaking Node 8 is also EOL as December, that was a short term version and is shown as EOL [here](https://github.com/nodejs/Release#end-of-life-releases)

**Comment by EisenbergEffect** [comment]
@3cp I had planned to use our cli to generate new skeletons. Somehow I kept forgetting, but I've got it on my list as a todo now. Does the cli properly generate SSR setups?

**Comment by 3cp** [comment]
I am aware nodejs v8 is EOL. I don't think cli offered any skeleton for SSR. We probably need that since skeleton-navigation repo is not maintained.

**Pull request merged**
