### PR TITLE
feat(mutation_observer): integrate MO polyfill

### PR DESCRIPTION
**Pull request by devanp92**
@martingust MO should be separated into another file - although, gulp didn't recognize ANY tests when I added a new file to src/.

Note that like @MeirionHughes as mentioned, the MO polyfill  does not detect text node changes - this will need to be implemented.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
For Aurelia, the text node change detection isn't needed. That would be
more of an issue if completeness more than anything.

**Comment by devanp92** [comment]
@EisenbergEffect Out of curiosity, why is text node change detection not needed?

**Comment by EisenbergEffect** [comment]
Actually, I forgot that the task queue does use that. We could provide an
alternate implementation for the server though.

**Comment by EisenbergEffect** [comment]
@MeirionHughes Can you review this?

**Comment by MeirionHughes** [comment]
@devanp92 did you go with a polyfil in the end or go with your own?

**Comment by devanp92** [comment]
@MeirionHughes I am using [megawc's polyfill](https://github.com/megawac/MutationObserver.js/blob/master/MutationObserver.js).

**Comment by MeirionHughes** [comment]
Okay, looks like that is effectively public domain licence; 

Yes, I think another restructure would be useful.

**Pull request merged**
